ALTER TABLE "Tournament" ADD COLUMN "registrationFeeNpr" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Tournament" ADD COLUMN "perKillPrizeNpr" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tournament" ADD COLUMN "fourthToTenthPrize" INTEGER NOT NULL DEFAULT 0;
